[package]
name = "rusty"
version = "0.1.0"
authors = ["Martin Chaine <martin@casimir.me>"]

[dependencies]
env_logger = "0.4"
image = "0.12"
log = "0.3"
rand = "0.3"
sdl2 = "0.28"
time = "0.1"

# vim: ft=ini
